### ISSUE TITLE
Integration with Poi 

### ISSUE THREAD

**Issue by IrvingArmenta** [pugjs/babel-plugin-transform-react-pug#49] opened 2018-07-03 01:40 UTC
Hello, I'm trying to use this plugin while using `poi` as my web bundler : https://poi.js.org/ 
I set up my `.babelrc` file like this:
```
{
  "presets": ["poi"],
  "plugins": [
          "react-hot-loader/babel",
          "transform-react-pug"
        ]
}

```
Since `poi` also uses the `.babelrc` file, but it keeps throwing me a syntax error when I try to use pug like this:
```
import React from 'react';

const Home = () => pug`
  .wrapper
    p.greeting Hello World!



export default Home;
```
but I get this error on the console: 
```
odule build failed: SyntaxError: /Users/irvingarmenta/Documents/irving/poi-bundler-test/components/Home.js: Unterminated template (3:23)

  1 | import React from 'react';
  2 |
> 3 | const Home = () => pug`
    |                        ^
  4 |   .wrapper
  5 |     p.greeting Hello World!
  6 |
    at _class.raise (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:3861:15)
    at _class.readTmplToken (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:4839:14)
    at TokContext.types$1.template [as override] (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:3058:14)
    at _class.nextToken (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:4069:18)
    at _class.next (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:4007:10)
    at _class.parseTemplate (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:6547:10)
    at _class.parseSubscript (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:5998:28)
    at _class.parseSubscripts (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:5888:19)
    at _class.parseExprSubscripts (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:5878:17)
    at _class.parseMaybeUnary (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:5847:21)
    at _class.parseExprOps (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:5754:21)
    at _class.parseMaybeConditional (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:5726:21)
    at _class.parseMaybeAssign (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:5673:21)
    at _class.parseFunctionBody (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:6857:24)
    at _class.parseArrowExpression (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:6817:10)
    at _class.parseParenAndDistinguishExpression (/Users/irvingarmenta/Documents/irving/poi-bundler-test/node_modules/@babel/parser/lib/index.js:6433:12)
```

Thought it was going to be a smooth implementation, however there seems to be an issue. Thank you.

**Comment by ljbc1994** [comment] 2018-07-03 06:33
Hi @IrvingArmenta!

It looks like your missing the closing quote ` in your template literal.

So if you do:

```js
const Home = () => pug`
  .wrapper
    p.greeting Hello World!
` // <- Missed out
```

This terminates the template, which is what `Unterminated template (3:23)` refers to.

**Comment by ezhlobo** [comment] 2018-07-16 07:37
@IrvingArmenta please, close the issue if the problem is solved ;).

**Closed** 2018-07-16 15:43 UTC
