### ISSUE TITLE
Use it with NextJs

### ISSUE THREAD

**Issue by Alfrex92** [pugjs/babel-plugin-transform-react-pug#51] opened 2018-07-06 18:12 UTC
Hi, thank you for the plugin. I tried with CRA and it is working. But, now I am doing a project with NextJS and I do not know what should I do to make it work.

Any suggestions? 
Thank you.

**Comment by ezhlobo** [comment] 2018-07-16 07:32
@Alfrex92 as far as I know nextjs allows you to setup custom `.babelrc` file. So everything you need is just to add this plugin to `.babelrc`.

**Comment by ezhlobo** [comment] 2018-08-23 15:56
I tried this plugin with Nextjs and got the error from babel. It said that current plugin crashes during converting a template.

The problem is that new babel@7 made some breaking changes. It was fixed within #48 by @shirohana. 

@Alfrex92 please, try new version `6.0.1` which contains the necessary fix. Feel free to re-open the issue if my answer is not helpful ;).

**Closed by ezhlobo** 2018-08-23 15:56 UTC
